In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

Collect Data + Preprocess Data

In [2]:
tickers = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0][['Symbol', 'GICS Sector']]
tickers['Symbol'] = tickers['Symbol'].str.replace('.', '-')
sector_breakdown = tickers.groupby('GICS Sector')['Symbol'].apply(list)
sector_breakdown = sector_breakdown.to_dict()

# Print the sector breakdown
print(sector_breakdown)

{'Communication Services': ['GOOGL', 'GOOG', 'T', 'CHTR', 'CMCSA', 'DIS', 'EA', 'FOXA', 'FOX', 'IPG', 'LYV', 'MTCH', 'META', 'NFLX', 'NWSA', 'NWS', 'OMC', 'PARA', 'TMUS', 'TTWO', 'VZ', 'WBD'], 'Consumer Discretionary': ['ABNB', 'AMZN', 'APTV', 'AZO', 'BBWI', 'BBY', 'BKNG', 'BWA', 'CZR', 'KMX', 'CCL', 'CMG', 'DHI', 'DRI', 'DPZ', 'EBAY', 'ETSY', 'EXPE', 'F', 'GRMN', 'GM', 'GPC', 'HAS', 'HLT', 'HD', 'LVS', 'LEN', 'LKQ', 'LOW', 'LULU', 'MAR', 'MCD', 'MGM', 'MHK', 'NKE', 'NCLH', 'NVR', 'ORLY', 'POOL', 'PHM', 'RL', 'ROST', 'RCL', 'SBUX', 'TPR', 'TSLA', 'TJX', 'TSCO', 'ULTA', 'VFC', 'WHR', 'WYNN', 'YUM'], 'Consumer Staples': ['ADM', 'MO', 'BF-B', 'BG', 'CPB', 'CHD', 'CLX', 'KO', 'CL', 'CAG', 'STZ', 'COST', 'DG', 'DLTR', 'EL', 'GIS', 'HSY', 'HRL', 'K', 'KVUE', 'KDP', 'KMB', 'KHC', 'KR', 'LW', 'MKC', 'TAP', 'MDLZ', 'MNST', 'PEP', 'PM', 'PG', 'SJM', 'SYY', 'TGT', 'TSN', 'WBA', 'WMT'], 'Energy': ['APA', 'BKR', 'CVX', 'COP', 'CTRA', 'DVN', 'FANG', 'EOG', 'EQT', 'XOM', 'HAL', 'HES', 'KMI', 'MRO', '

In [3]:
ticker_list = []
for sector in sector_breakdown:
    ticker_list.extend(sector_breakdown[sector])

today = pd.Timestamp.today().strftime('%Y-%m-%d')
month_ago = pd.Timestamp.today() - pd.DateOffset(months=1)

data = yf.download(ticker_list, start=month_ago, end=today)
#data = data.drop(columns=['Open', 'High', 'Low', 'Close', 'Volume'])
data

[*********************100%%**********************]  503 of 503 completed


5 Failed downloads:
['SJM', 'V', 'TMUS', 'VICI', 'BX']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2023-10-30 02:25:29.664089 -> 2023-11-30)')


Adj Close                                             \
                              A    AAL        AAPL        ABBV        ABNB   
Date                                                                         
2023-10-30 00:00:00  101.169998  11.18  170.065933  141.889999  116.949997   
2023-10-31 00:00:00  103.370003  11.15  170.545319  141.179993  118.290001   
2023-11-01 00:00:00  102.860001  11.14  173.741104  142.470001  119.470001   
2023-11-02 00:00:00  104.470001  11.40  177.336380  143.259995  115.500000   
2023-11-03 00:00:00  109.019997  11.98  176.417572  141.419998  122.639999   
2023-11-06 00:00:00  107.529999  11.66  178.994186  141.199997  118.169998   
2023-11-07 00:00:00  110.540001  11.75  181.580780  142.160004  121.080002   
2023-11-08 00:00:00  109.389999  12.01  182.649368  142.029999  117.660004   
2023-11-09 00:00:00  107.739998  11.75  182.169998  138.039993  115.519997   
2023-11-10 00:00:00  108.470001  11.80  186.399994  138.589996  118.150002   
2023-11-13 00:00:00  107.459999  11.78  184.800003  138.639999  119.150002   
2023-11-14 00:00:00  111.610001  12.25  187.440002  138.059998  126.680000   
2023-11-15 00:00:00  113.599998  12.42  188.009995  137.600006  128.350006   
2023-11-16 00:00:00  114.190002  12.19  189.710007  138.279999  126.279999   
2023-11-17 00:00:00  113.150002  12.29  189.690002  138.300003  127.150002   
2023-11-20 00:00:00  113.980003  12.40  191.449997  138.309998  129.699997   
2023-11-21 00:00:00  123.919998  12.13  190.639999  138.729996  126.820000   
2023-11-22 00:00:00  123.989998  12.31  191.309998  138.470001  129.039993   
2023-11-24 00:00:00  126.620003  12.31  189.970001  138.669998  128.369995   
2023-11-27 00:00:00  125.010002  12.18  189.789993  139.089996  129.000000   
2023-11-28 00:00:00  124.709999  12.17  190.399994  138.080002  127.559998   
2023-11-29 00:00:00  127.589996  12.23  189.369995  138.500000  126.480003   

                                                                    \
                            ABT       ACGL         ACN        ADBE   
Date                                                                 
2023-10-30 00:00:00   93.000000  82.879997  292.700012  526.940002   
2023-10-31 00:00:00   94.550003  86.680000  297.089996  532.059998   
2023-11-01 00:00:00   95.010002  90.000000  300.640015  544.500000   
2023-11-02 00:00:00   95.959999  85.940002  308.119995  558.710022   
2023-11-03 00:00:00   95.839996  85.550003  313.489990  563.659973   
2023-11-06 00:00:00   95.000000  85.160004  313.089996  565.450012   
2023-11-07 00:00:00   94.800003  85.410004  315.190002  585.200012   
2023-11-08 00:00:00   94.739998  84.120003  317.820007  585.309998   
2023-11-09 00:00:00   93.550003  84.669998  314.220001  577.739990   
2023-11-10 00:00:00   93.970001  85.949997  319.690002  597.219971   
2023-11-13 00:00:00   95.790001  86.570000  315.630005  590.340027   
2023-11-14 00:00:00   97.080002  85.500000  320.489990  604.330017   
2023-11-15 00:00:00   98.000000  82.660004  325.500000  595.309998   
2023-11-16 00:00:00  100.260002  83.709999  327.320007  602.059998   
2023-11-17 00:00:00   99.550003  83.599998  327.829987  602.659973   
2023-11-20 00:00:00  101.199997  84.459999  330.899994  612.700012   
2023-11-21 00:00:00  101.910004  86.129997  330.260010  610.989990   
2023-11-22 00:00:00  102.699997  85.949997  333.130005  619.719971   
2023-11-24 00:00:00  102.870003  86.599998  334.040009  619.429993   
2023-11-27 00:00:00  102.709999  87.000000  332.429993  619.270020   
2023-11-28 00:00:00  102.059998  84.449997  332.559998  623.320007   
2023-11-29 00:00:00  103.629997  82.379997  333.339996  617.390015   

                                 ...    Volume                              \
                            ADI  ...      WYNN      XEL       XOM     XRAY   
Date                             ...                                         
2023-10-30 00:00:00  155.880005  ...   1343100  3818400  19379900  3388500   
2023-10-

In [4]:
# Backward fill NaN values
data = data.fillna(method='bfill', axis=0)

# Backward fill NaN values
data = data.fillna(method='ffill', axis=0)

# Print number of NA values across each column
print(data.isna().sum(axis=1))

Date
2023-10-30 00:00:00    30
2023-10-31 00:00:00    30
2023-11-01 00:00:00    30
2023-11-02 00:00:00    30
2023-11-03 00:00:00    30
2023-11-06 00:00:00    30
2023-11-07 00:00:00    30
2023-11-08 00:00:00    30
2023-11-09 00:00:00    30
2023-11-10 00:00:00    30
2023-11-13 00:00:00    30
2023-11-14 00:00:00    30
2023-11-15 00:00:00    30
2023-11-16 00:00:00    30
2023-11-17 00:00:00    30
2023-11-20 00:00:00    30
2023-11-21 00:00:00    30
2023-11-22 00:00:00    30
2023-11-24 00:00:00    30
2023-11-27 00:00:00    30
2023-11-28 00:00:00    30
2023-11-29 00:00:00    30
dtype: int64


C:\Users\ayush\AppData\Local\Temp\ipykernel_27348\1922356623.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data = data.fillna(method='bfill', axis=0)
C:\Users\ayush\AppData\Local\Temp\ipykernel_27348\1922356623.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data = data.fillna(method='ffill', axis=0)


In [5]:
# Calculate daily returns
returns = data.pct_change()

# Drop the index name Adj Close
returns = returns.droplevel(0, axis=1)

# Group tickers in returns dataframe by sector using sector_breakdown's keys & values
sector_mean_returns = {}

# Extract each key & value pair from sector_breakdown
for sector, tickers in sector_breakdown.items():
    # Get tickers for each sector
    sector_data = returns[tickers]

    # Calculate mean returns for each sector and add to dictionary
    sector_mean_returns[sector] = sector_data.mean(axis=1)

# Convert sector_mean_returns dict to a DataFrame
sector_mean_returns = pd.DataFrame(sector_mean_returns)

sector_mean_returns

C:\Users\ayush\AppData\Local\Temp\ipykernel_27348\677370838.py:2: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Call ffill before calling pct_change to retain current behavior and silence this warning.
  returns = data.pct_change()


Communication Services  Consumer Discretionary  \
Date                                                                  
2023-10-30 00:00:00                     NaN                     NaN   
2023-10-31 00:00:00                0.008071                0.013324   
2023-11-01 00:00:00                0.023782                0.036075   
2023-11-02 00:00:00                0.039465                0.041363   
2023-11-03 00:00:00                0.018494                0.017333   
2023-11-06 00:00:00               -0.030178               -0.024006   
2023-11-07 00:00:00                0.003611                0.004221   
2023-11-08 00:00:00                0.074299                0.008652   
2023-11-09 00:00:00               -0.002027                0.002107   
2023-11-10 00:00:00                0.003201                0.005872   
2023-11-13 00:00:00               -0.030227               -0.003081   
2023-11-14 00:00:00                0.070964                0.113779   
2023-11-15 00:00:00               -0.002480                0.014807   
2023-11-16 00:00:00                0.059102               -0.022683   
2023-11-17 00:00:00               -0.005366               -0.000777   
2023-11-20 00:00:00                0.022713               -0.003383   
2023-11-21 00:00:00               -0.015858               -0.002853   
2023-11-22 00:00:00               -0.010351               -0.013715   
2023-11-24 00:00:00               -0.082242               -0.082477   
2023-11-27 00:00:00                0.275804                0.257042   
2023-11-28 00:00:00                0.001280                0.006808   
2023-11-29 00:00:00                0.016217                0.063004   

                     Consumer Staples    Energy  Financials  Health Care  \
Date                                                                       
2023-10-30 00:00:00               NaN       NaN         NaN          NaN   
2023-10-31 00:00:00          0.049119  0.000853    0.036078     0.022375   
2023-11-01 00:00:00          0.013096  0.026973    0.013687     0.006983   
2023-11-02 00:00:00          0.014211  0.033533    0.053674     0.026280   
2023-11-03 00:00:00         -0.001321 -0.001097    0.011471     0.017257   
2023-11-06 00:00:00         -0.009287 -0.035832   -0.034201    -0.003759   
2023-11-07 00:00:00         -0.015622  0.054382   -0.016027     0.006843   
2023-11-08 00:00:00          0.036963 -0.017635    0.002870     0.005820   
2023-11-09 00:00:00         -0.004962 -0.030868    0.014971     0.002733   
2023-11-10 00:00:00          0.013160  0.010144   -0.001351     0.019914   
2023-11-13 00:00:00          0.007143 -0.021318   -0.002956     0.004744   
2023-11-14 00:00:00          0.043012  0.044602    0.129906     0.048558   
2023-11-15 00:00:00          0.031297  0.029425   -0.001104     0.033997   
2023-11-16 00:00:00          0.023785  0.026881   -0.015829    -0.016031   
2023-11-17 00:00:00         -0.008106 -0.006823   -0.001788     0.012955   
2023-11-20 00:00:00         -0.014977 -0.027029    0.001325    -0.007272   
2023-11-21 00:00:00          0.007431 -0.025540   -0.004565     0.012980   
2023-11-22 00:00:00         -0.012233  0.020083   -0.023557    -0.031890   
2023-11-24 00:00:00         -0.080742 -0.077275   -0.077205    -0.076846   
2023-11-27 00:00:00          0.239609  0.200329    0.254820     0.270134   
2023-11-28 00:00:00          0.015028 -0.002494    0.020433     0.000886   
2023-11-29 00:00:00          0.000382  0.071427    0.036455     0.057962   

                     Industrials  Information Technology  Materials  \
Date                                                                  
2023-10-30 00:00:00          NaN                     NaN        NaN   
2023-10-31 00:00:00     0.054567                0.017828   0.036551   
2023-11-01 00:00:00     0.028862                0.044617   0.023466   
2023-11-02 00:00:00     0.024113                0.035161   0.001615   
2023-11-03 00:00:00     0.000788                0.008732   0.0100

In [6]:
# Drop rows that have NaN values
sector_mean_returns = sector_mean_returns.dropna()
sector_mean_returns

Communication Services  Consumer Discretionary  \
Date                                                                  
2023-10-31 00:00:00                0.008071                0.013324   
2023-11-01 00:00:00                0.023782                0.036075   
2023-11-02 00:00:00                0.039465                0.041363   
2023-11-03 00:00:00                0.018494                0.017333   
2023-11-06 00:00:00               -0.030178               -0.024006   
2023-11-07 00:00:00                0.003611                0.004221   
2023-11-08 00:00:00                0.074299                0.008652   
2023-11-09 00:00:00               -0.002027                0.002107   
2023-11-10 00:00:00                0.003201                0.005872   
2023-11-13 00:00:00               -0.030227               -0.003081   
2023-11-14 00:00:00                0.070964                0.113779   
2023-11-15 00:00:00               -0.002480                0.014807   
2023-11-16 00:00:00                0.059102               -0.022683   
2023-11-17 00:00:00               -0.005366               -0.000777   
2023-11-20 00:00:00                0.022713               -0.003383   
2023-11-21 00:00:00               -0.015858               -0.002853   
2023-11-22 00:00:00               -0.010351               -0.013715   
2023-11-24 00:00:00               -0.082242               -0.082477   
2023-11-27 00:00:00                0.275804                0.257042   
2023-11-28 00:00:00                0.001280                0.006808   
2023-11-29 00:00:00                0.016217                0.063004   

                     Consumer Staples    Energy  Financials  Health Care  \
Date                                                                       
2023-10-31 00:00:00          0.049119  0.000853    0.036078     0.022375   
2023-11-01 00:00:00          0.013096  0.026973    0.013687     0.006983   
2023-11-02 00:00:00          0.014211  0.033533    0.053674     0.026280   
2023-11-03 00:00:00         -0.001321 -0.001097    0.011471     0.017257   
2023-11-06 00:00:00         -0.009287 -0.035832   -0.034201    -0.003759   
2023-11-07 00:00:00         -0.015622  0.054382   -0.016027     0.006843   
2023-11-08 00:00:00          0.036963 -0.017635    0.002870     0.005820   
2023-11-09 00:00:00         -0.004962 -0.030868    0.014971     0.002733   
2023-11-10 00:00:00          0.013160  0.010144   -0.001351     0.019914   
2023-11-13 00:00:00          0.007143 -0.021318   -0.002956     0.004744   
2023-11-14 00:00:00          0.043012  0.044602    0.129906     0.048558   
2023-11-15 00:00:00          0.031297  0.029425   -0.001104     0.033997   
2023-11-16 00:00:00          0.023785  0.026881   -0.015829    -0.016031   
2023-11-17 00:00:00         -0.008106 -0.006823   -0.001788     0.012955   
2023-11-20 00:00:00         -0.014977 -0.027029    0.001325    -0.007272   
2023-11-21 00:00:00          0.007431 -0.025540   -0.004565     0.012980   
2023-11-22 00:00:00         -0.012233  0.020083   -0.023557    -0.031890   
2023-11-24 00:00:00         -0.080742 -0.077275   -0.077205    -0.076846   
2023-11-27 00:00:00          0.239609  0.200329    0.254820     0.270134   
2023-11-28 00:00:00          0.015028 -0.002494    0.020433     0.000886   
2023-11-29 00:00:00          0.000382  0.071427    0.036455     0.057962   

                     Industrials  Information Technology  Materials  \
Date                                                                  
2023-10-31 00:00:00     0.054567                0.017828   0.036551   
2023-11-01 00:00:00     0.028862                0.044617   0.023466   
2023-11-02 00:00:00     0.024113                0.035161   0.001615   
2023-11-03 00:00:00     0.000788                0.008732   0.010025   
2023-11-06 00:00:00    -0.031583               -0.023917  -0.010962   
2023-11-07 00:00:00     0.008701                0.013361   0.053620   
2023-11-08 00:00:00     0.017837                0.000945  -0.017990   

In [7]:
# Calculate the variance-covariance matrix for the 11 sector returns
cov_matrix = sector_mean_returns.cov()
cov_matrix

Communication Services  Consumer Discretionary  \
Communication Services                0.004665                0.004046   
Consumer Discretionary                0.004046                0.004306   
Consumer Staples                      0.003683                0.003424   
Energy                                0.003201                0.003245   
Financials                            0.004090                0.004290   
Health Care                           0.003880                0.003997   
Industrials                           0.003731                0.003779   
Information Technology                0.003544                0.003643   
Materials                             0.005067                0.004941   
Real Estate                           0.005332                0.005543   
Utilities                             0.004721                0.004527   

                        Consumer Staples    Energy  Financials  Health Care  \
Communication Services          0.003683  0.003201    0.004090     0.003880   
Consumer Discretionary          0.003424  0.003245    0.004290     0.003997   
Consumer Staples                0.003352  0.002653    0.003487     0.003467   
Energy                          0.002653  0.003050    0.003072     0.003108   
Financials                      0.003487  0.003072    0.004450     0.003939   
Health Care                     0.003467  0.003108    0.003939     0.004064   
Industrials                     0.003312  0.002832    0.003866     0.003585   
Information Technology          0.002950  0.002839    0.003641     0.003364   
Materials                       0.004413  0.003853    0.004978     0.004972   
Real Estate                     0.004461  0.003995    0.005778     0.005123   
Utilities                       0.004102  0.003490    0.004599     0.004359   

                        Industrials  Information Technology  Materials  \
Communication Services     0.003731                0.003544   0.005067   
Consumer Discretionary     0.003779                0.003643   0.004941   
Consumer Staples           0.003312                0.002950   0.004413   
Energy                     0.002832                0.002839   0.003853   
Financials                 0.003866                0.003641   0.004978   
Health Care                0.003585                0.003364   0.004972   
Industrials                0.003669                0.003244   0.004685   
Information Technology     0.003244                0.003197   0.004266   
Materials                  0.004685                0.004266   0.006868   
Real Estate                0.005010                0.004697   0.006670   
Utilities                  0.004294                0.003885   0.005735   

                        Real Estate  Utilities  
Communication Services     0.005332   0.004721  
Consumer Discretionary     0.005543   0.004527  
Consumer Staples           0.004461   0.004102  
Energy                     0.003995   0.003490  
Financials                 0.005778   0.004599  
Health Care                0.005123   0.004359  
Industrials                0.005010   0.004294  
Information Technology     0.004697   0.003885  
Materials                  0.006670   0.005735  
Real Estate                0.007764   0.005993  
Utilities                  0.005993   0.005386

Black-Litterman Model

In [8]:
class BlackLittermanModel:
    def __init__(self, market_equilibrium_returns, covariance_matrix, views, confidence_matrix):
        self.market_equilibrium_returns = market_equilibrium_returns
        self.covariance_matrix = covariance_matrix
        self.views = views
        self.confidence_matrix = confidence_matrix

    def calculate_bl_expected_returns(self):
        """
        Calculate expected returns using the Black-Litterman model.
        """
        tau = 0.025  # Tau is the scaling factor, adjust as needed

        # Calculate the equilibrium excess returns
        pi = np.dot(self.covariance_matrix, self.market_equilibrium_returns)

        # Calculate the Black-Litterman expected returns
        bl_expected_returns = np.dot(
            np.linalg.inv(np.linalg.inv(tau * self.covariance_matrix) + np.dot(np.dot(self.views.T, np.linalg.inv(self.confidence_matrix)), self.views)),
            np.dot(np.linalg.inv(tau * self.covariance_matrix), pi) + np.dot(np.dot(self.views.T, np.linalg.inv(self.confidence_matrix)), self.views.T.dot(self.views.dot(self.market_equilibrium_returns)))
        )

        return bl_expected_returns

In [9]:
# Assuming you have a risk-free rate and equity risk premium
risk_free_rate = 0.047  # Adjust based on the current risk-free rate
equity_risk_premium = 0.06  # Adjust based on economic indicators

# Calculate market equilibrium returns
market_equilibrium_returns = risk_free_rate + equity_risk_premium + sector_mean_returns.mean(axis=0)

# Print the market equilibrium returns
print("Market Equilibrium Returns:")
print(market_equilibrium_returns)


Market Equilibrium Returns:
Communication Services    0.127870
Consumer Discretionary    0.127543
Consumer Staples          0.123523
Energy                    0.119987
Financials                0.125910
Health Care               0.126744
Industrials               0.125425
Information Technology    0.126551
Materials                 0.128964
Real Estate               0.129524
Utilities                 0.127757
dtype: float64


In [10]:
# Define the sectors in your portfolio
sectors = [
    'Communication Services',
    'Consumer Discretionary',
    'Consumer Staples',
    'Energy',
    'Financials',
    'Health Care',
    'Industrials',
    'Information Technology',
    'Materials',
    'Real Estate',
    'Utilities'
]

# Assuming you have len(sectors) assets in your portfolio
n_assets = len(sectors)

# Define your views based on your analysis
views = np.zeros(n_assets)

# Replace the values below with your own views for each sector
views[0] = 0.02  # Positive view on Communication Services
views[1] = -0.01  # Negative view on Consumer Discretionary
views[2] = 0.015   # Positive view on Consumer Staples
views[3] = -0.02  # Negative view on Energy
views[4] = 0.01  # Positive view on Financials
views[5] = 0.005  # Slightly positive view on Health Care
views[6] = -0.015  # Negative view on Industrials
views[7] = 0.03  # Positive view on Information Technology
views[8] = -0.01  # Negative view on Materials
views[9] = 0.005  # Slightly positive view on Real Estate
views[10] = -0.02  # Negative view on Utilities

print("Your Views:")
print(views)

# Ensure that the sum of views is zero for market equilibrium
views = views - np.mean(views)
print("Adjusted Views:")
print(views)

# Define confidence levels for each view
confidence_levels = {
    'Communication Services': 0.09,
    'Consumer Discretionary': 0.09,
    'Consumer Staples': 0.09,
    'Energy': 0.09,
    'Financials': 0.09,
    'Health Care': 0.09,
    'Industrials': 0.09,
    'Information Technology': 0.09,
    'Materials': 0.09,
    'Real Estate': 0.09,
    'Utilities': 0.09,
}

# Create a diagonal matrix using the confidence levels
confidence_matrix = np.diag([confidence_levels[sectors[i]] for i in range(n_assets)])


Your Views:
[ 0.02  -0.01   0.015 -0.02   0.01   0.005 -0.015  0.03  -0.01   0.005
 -0.02 ]
Adjusted Views:
[ 0.01909091 -0.01090909  0.01409091 -0.02090909  0.00909091  0.00409091
 -0.01590909  0.02909091 -0.01090909  0.00409091 -0.02090909]


In [11]:
# Assuming you have market_equilibrium_returns, covariance_matrix, investor_views, and confidence_matrix defined
bl_model = BlackLittermanModel(market_equilibrium_returns, cov_matrix, views, confidence_matrix)
bl_expected_returns = bl_model.calculate_bl_expected_returns()

# Print the Black-Litterman expected returns
print("Black-Litterman Expected Returns:")
print(bl_expected_returns)

Black-Litterman Expected Returns:
[0.00581976 0.00579178 0.00497619 0.00447063 0.0058503  0.0055531
 0.0053194  0.00497208 0.00714946 0.00764714 0.0064695 ]


LSTM Model

In [14]:
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [36]:
def create_sequences(data, sequence_length):
    """
    Create input sequences for LSTM model.

    Parameters:
    - data: numpy array, input data (scaled returns)
    - sequence_length: int, length of each sequence

    Returns:
    - X: numpy array, input sequences
    - y: numpy array, corresponding output values
    """
    X, y = [], []

    for i in range(len(data) - sequence_length):
        sequence = data[i:i + sequence_length]
        target = data[i + sequence_length]
        X.append(sequence)
        y.append(target)

    return np.array(X), np.array(y)


In [59]:
# Assuming you have already calculated mean_returns
equilibrium_expected_returns = risk_free_rate + equity_risk_premium + sector_mean_returns.mean(axis=0)

# Print Equilibrium Expected Returns
print("Equilibrium Expected Returns:")
print(equilibrium_expected_returns)

# Assuming you have already loaded the data and calculated returns
cov_matrix = sector_mean_returns.cov()

# Print Covariance Matrix
print("Covariance Matrix:")
print(cov_matrix)

# LSTM-based Portfolio Optimization

# Prepare data for LSTM
returns_data = sector_mean_returns[sectors].copy()
scaler_lstm = MinMaxScaler(feature_range=(0, 1))
scaled_returns_data = scaler_lstm.fit_transform(returns_data)

# Create input sequences for LSTM
sequence_length_lstm = 10
sequences_lstm, targets_lstm = create_sequences(scaled_returns_data, sequence_length_lstm)

# Split data into train and test sets
train_size_lstm = int(len(sequences_lstm) * 0.8)
train_lstm, test_lstm = sequences_lstm[:train_size_lstm], sequences_lstm[train_size_lstm:]
train_targets, test_targets = targets_lstm[:train_size_lstm], targets_lstm[train_size_lstm:]

# Extract features (X) and target variable (y) for LSTM
X_train_lstm, y_train_lstm = train_lstm[:, :-1, :], train_targets
X_test_lstm, y_test_lstm = test_lstm[:, :-1, :], test_targets

# Reshape input data for LSTM (batch_size, time_steps, features)
X_train_lstm = np.reshape(X_train_lstm, (X_train_lstm.shape[0], X_train_lstm.shape[1], X_train_lstm.shape[2]))
X_test_lstm = np.reshape(X_test_lstm, (X_test_lstm.shape[0], X_test_lstm.shape[1], X_test_lstm.shape[2]))

print("X_train_lstm shape:", X_train_lstm.shape)
print("y_train_lstm shape:", y_train_lstm.shape)



Equilibrium Expected Returns:
Communication Services    0.127870
Consumer Discretionary    0.127543
Consumer Staples          0.123523
Energy                    0.119987
Financials                0.125910
Health Care               0.126744
Industrials               0.125425
Information Technology    0.126551
Materials                 0.128964
Real Estate               0.129524
Utilities                 0.127757
dtype: float64
Covariance Matrix:
                        Communication Services  Consumer Discretionary  \
Communication Services                0.004665                0.004046   
Consumer Discretionary                0.004046                0.004306   
Consumer Staples                      0.003683                0.003424   
Energy                                0.003201                0.003245   
Financials                            0.004090                0.004290   
Health Care                           0.003880                0.003997   
Industrials                      

In [68]:
# Build a separate LSTM model for each sector
models_lstm = []
predictions_lstm = []

for i in range(len(sectors)):
    # Build LSTM model
    model_lstm = Sequential()
    model_lstm.add(LSTM(units=50, return_sequences=True, input_shape=(X_train_lstm.shape[1], X_train_lstm.shape[2])))
    model_lstm.add(LSTM(units=50))
    model_lstm.add(Dense(units=1))
    model_lstm.compile(optimizer='adam', loss='mean_squared_error')

    # Train the LSTM model
    model_lstm.fit(X_train_lstm, y_train_lstm[:, i], epochs=10, batch_size=32)

    # Make predictions on the test set
    predictions_sector = model_lstm.predict(X_test_lstm)
    predictions_lstm.append(predictions_sector)

    # Save the model for each sector
    models_lstm.append(model_lstm)

Epoch 1/10
1/1 [==============================] - 5s 5s/step - loss: 0.0875
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 0.0522
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 0.0294
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 0.0181
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 0.0169
Epoch 6/10
1/1 [==============================] - 0s 14ms/step - loss: 0.0222
Epoch 7/10
1/1 [==============================] - 0s 15ms/step - loss: 0.0273
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 0.0285
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 0.0263
Epoch 10/10
1/1 [==============================] - 1s 706ms/step
Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 0.1283
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 0.0859
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 0.0554
Epo

In [69]:
# Convert predictions list to numpy array
predictions_lstm = np.array(predictions_lstm)

# Reshape predictions back to the original shape
predictions_lstm = np.reshape(predictions_lstm, (predictions_lstm.shape[1], predictions_lstm.shape[0]))

# Inverse transform the predictions using the scaler
predicted_returns_lstm = scaler_lstm.inverse_transform(predictions_lstm)

# Reshape back to the original shape
predicted_returns_lstm = np.reshape(predicted_returns_lstm, (predicted_returns_lstm.shape[0], len(sectors)))

# Print the predicted returns for each sector
for i, sector in enumerate(sectors):
    print(f"Predicted Returns for {sector}:")
    print(predicted_returns_lstm[:, i])

Predicted Returns for Communication Services:
[0.02434757 0.05613302 0.03921209]
Predicted Returns for Consumer Discretionary:
[0.01357014 0.02432707 0.0434005 ]
Predicted Returns for Consumer Staples:
[ 0.01719658  0.01319217 -0.03234709]
Predicted Returns for Energy:
[ 0.01813755  0.01285798 -0.03731747]
Predicted Returns for Financials:
[ 0.03060976  0.00158547 -0.02581918]
Predicted Returns for Health Care:
[0.04559514 0.00140647 0.00863026]
Predicted Returns for Industrials:
[ 0.01003616 -0.00820204 -0.01337863]
Predicted Returns for Information Technology:
[ 0.00157515  0.0296284  -0.00968123]
Predicted Returns for Materials:
[0.06229734 0.08437207 0.02964238]
Predicted Returns for Real Estate:
[0.07615241 0.08375987 0.01355051]
Predicted Returns for Utilities:
[0.04883568 0.05304671 0.00580595]


In [77]:
# Initialize an empty dictionary to store combined expected returns for each sector
combined_expected_returns_by_sector = {}
weight_lstm = 0.2

# Iterate through each sector
for sector in sectors:
    # Equilibrium expected returns for the current sector
    equilibrium_expected_returns_sector = equilibrium_expected_returns[sector]

    try:
        # LSTM predictions for the current sector
        predicted_returns_lstm_sector = predicted_returns_lstm[sectors.index(sector)]
    except IndexError:
        print(f"Skipping {sector} because it doesn't have LSTM predictions.")
        continue

    # Combine expected returns for the current sector
    combined_expected_returns_sector = equilibrium_expected_returns_sector + weight_lstm * predicted_returns_lstm_sector

    # Store the combined expected returns for the current sector
    combined_expected_returns_by_sector[sector] = combined_expected_returns_sector

# Print the combined expected returns for each sector
for sector, combined_returns in combined_expected_returns_by_sector.items():
    print(f"Combined Expected Returns for {sector}:")
    print(combined_returns)
    print()


Skipping Energy because it doesn't have LSTM predictions.
Skipping Financials because it doesn't have LSTM predictions.
Skipping Health Care because it doesn't have LSTM predictions.
Skipping Industrials because it doesn't have LSTM predictions.
Skipping Information Technology because it doesn't have LSTM predictions.
Skipping Materials because it doesn't have LSTM predictions.
Skipping Real Estate because it doesn't have LSTM predictions.
Skipping Utilities because it doesn't have LSTM predictions.
Combined Expected Returns for Communication Services:
[0.13273974 0.13058424 0.13130954 0.13149773 0.13399217 0.13698925
 0.12987745 0.12818524 0.14032969 0.1431007  0.13763735]

Combined Expected Returns for Consumer Discretionary:
[0.13877001 0.13240881 0.13018183 0.130115   0.1278605  0.1278247
 0.125903   0.13346909 0.14441782 0.14429538 0.13815275]

Combined Expected Returns for Consumer Staples:
[0.13136551 0.13220319 0.11705367 0.1160596  0.11835926 0.12524915
 0.12084737 0.12158684 

Combine Black-Litterman and LSTM

In [86]:
# Assuming you have already calculated mean_returns for the LSTM predictions
equilibrium_expected_returns_lstm = risk_free_rate + equity_risk_premium + predicted_returns_lstm.mean(axis=0)

# Assuming you have already loaded the data and calculated returns for the LSTM predictions
cov_matrix_lstm = np.cov(predicted_returns_lstm, rowvar=False)

# Align LSTM predictions with sectors
aligned_predicted_returns_lstm = np.zeros(len(sectors))
for i in range(len(sectors)):
    if i < len(predicted_returns_lstm):
        # Take the average of the predictions for the current sector
        aligned_predicted_returns_lstm[i] = np.mean(predicted_returns_lstm[i])
    else:
        # Handle the case when the sector is not present in LSTM predictions
        print(f"Skipping {sectors[i]} because it doesn't have LSTM predictions.")
        aligned_predicted_returns_lstm[i] = 0  # You can set a default value or handle it differently

# Combine Expected Returns
combined_expected_returns = equilibrium_expected_returns + weight_lstm * aligned_predicted_returns_lstm

# Print Combined Expected Returns
print("Combined Expected Returns:")
print(combined_expected_returns)


Skipping Energy because it doesn't have LSTM predictions.
Skipping Financials because it doesn't have LSTM predictions.
Skipping Health Care because it doesn't have LSTM predictions.
Skipping Industrials because it doesn't have LSTM predictions.
Skipping Information Technology because it doesn't have LSTM predictions.
Skipping Materials because it doesn't have LSTM predictions.
Skipping Real Estate because it doesn't have LSTM predictions.
Skipping Utilities because it doesn't have LSTM predictions.
Combined Expected Returns:
Communication Services    0.134204
Consumer Discretionary    0.133945
Consumer Staples          0.123918
Energy                    0.119987
Financials                0.125910
Health Care               0.126744
Industrials               0.125425
Information Technology    0.126551
Materials                 0.128964
Real Estate               0.129524
Utilities                 0.127757
dtype: float64


In [88]:
# Combine Covariance Matrices
combined_cov_matrix = (1 - weight_lstm) * cov_matrix + weight_lstm * cov_matrix_lstm

combined_cov_matrix

Communication Services  Consumer Discretionary  \
Communication Services                0.003782                0.003252   
Consumer Discretionary                0.003252                0.003491   
Consumer Staples                      0.002943                0.002660   
Energy                                0.002556                0.002507   
Financials                            0.003228                0.003348   
Health Care                           0.003035                0.003149   
Industrials                           0.002957                0.002990   
Information Technology                0.002882                0.002889   
Materials                             0.004092                0.003893   
Real Estate                           0.004283                0.004330   
Utilities                             0.003787                0.003551   

                        Consumer Staples    Energy  Financials  Health Care  \
Communication Services          0.002943  0.002556    0.003228     0.003035   
Consumer Discretionary          0.002660  0.002507    0.003348     0.003149   
Consumer Staples                0.002833  0.002291    0.002928     0.002830   
Energy                          0.002291  0.002627    0.002613     0.002551   
Financials                      0.002928  0.002613    0.003720     0.003257   
Health Care                     0.002830  0.002551    0.003257     0.003364   
Industrials                     0.002698  0.002321    0.003159     0.002922   
Information Technology          0.002435  0.002353    0.002943     0.002654   
Materials                       0.003665  0.003231    0.004072     0.003972   
Real Estate                     0.003778  0.003428    0.004797     0.004148   
Utilities                       0.003424  0.002950    0.003799     0.003522   

                        Industrials  Information Technology  Materials  \
Communication Services     0.002957                0.002882   0.004092   
Consumer Discretionary     0.002990                0.002889   0.003893   
Consumer Staples           0.002698                0.002435   0.003665   
Energy                     0.002321                0.002353   0.003231   
Financials                 0.003159                0.002943   0.004072   
Health Care                0.002922                0.002654   0.003972   
Industrials                0.002965                0.002594   0.003770   
Information Technology     0.002594                0.002640   0.003517   
Materials                  0.003770                0.003517   0.005646   
Real Estate                0.004064                0.003880   0.005538   
Utilities                  0.003474                0.003190   0.004724   

                        Real Estate  Utilities  
Communication Services     0.004283   0.003787  
Consumer Discretionary     0.004330   0.003551  
Consumer Staples           0.003778   0.003424  
Energy                     0.003428   0.002950  
Financials                 0.004797   0.003799  
Health Care                0.004148   0.003522  
Industrials                0.004064   0.003474  
Information Technology     0.003880   0.003190  
Materials                  0.005538   0.004724  
Real Estate                0.006508   0.004996  
Utilities                  0.004996   0.004446

Calculate Allocations

In [94]:
# Calculate the inverse of the combined covariance matrix
inv_combined_cov_matrix = np.linalg.inv(combined_cov_matrix)

# Calculate the expected excess returns
expected_excess_returns = combined_expected_returns

# Calculate the Black-Litterman expected returns
bl_expected_returns = np.dot(inv_combined_cov_matrix, expected_excess_returns)

# Normalize weights to get allocations
allocations = bl_expected_returns / np.sum(bl_expected_returns)

# Make sure allocations are non-negative
allocations[allocations < 0] = 0

# Normalize again to ensure the sum is 1
allocations /= np.sum(allocations)


# Print the allocations for each sector
for sector, allocation in zip(sectors, allocations):
    print(f"Allocation for {sector}: {allocation:.4f}")

Allocation for Communication Services: 0.0296
Allocation for Consumer Discretionary: 0.0127
Allocation for Consumer Staples: 0.2933
Allocation for Energy: 0.0611
Allocation for Financials: 0.1470
Allocation for Health Care: 0.0000
Allocation for Industrials: 0.1871
Allocation for Information Technology: 0.2691
Allocation for Materials: 0.0000
Allocation for Real Estate: 0.0000
Allocation for Utilities: 0.0000


 Evaluate Portfolio Performance

In [91]:
def evaluate_portfolio(returns, weights):
    # Calculate annualized portfolio return
    annual_portfolio_return = np.sum(returns.mean() * weights) * 252

    # Calculate annualized portfolio volatility
    portfolio_volatility = np.sqrt(np.dot(weights.T, np.dot(returns.cov() * 252, weights)))

    # Assuming risk-free rate is 0 for simplicity
    risk_free_rate = 0

    # Calculate Sharpe ratio
    sharpe_ratio = (annual_portfolio_return - risk_free_rate) / portfolio_volatility

    return annual_portfolio_return, portfolio_volatility, sharpe_ratio

# Assuming you have a DataFrame 'returns_data' containing returns for each sector
# Assuming 'allocations' contains the weights/allocations for each sector

# Evaluate portfolio performance
portfolio_return, portfolio_volatility, sharpe_ratio = evaluate_portfolio(returns_data, allocations)

# Print the results
print(f"Annual Portfolio Return: {portfolio_return:.4f}")
print(f"Annual Portfolio Volatility: {portfolio_volatility:.4f}")
print(f"Sharpe Ratio: {sharpe_ratio:.4f}")


Annual Portfolio Return: 4.5382
Annual Portfolio Volatility: 0.9158
Sharpe Ratio: 4.9552
